spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://postgres:5432/user_service
    username: admin
    password: secret123
  security:
    jwt:
      secret: "BmotNKeNwGD6tal1SonRj7jtdXEXEYQlSECQcRbW6bpJYfYppEoGE0eIk1CvUX7VxhbI9MgR3ZOEzUWnlOvHNw"
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
